---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 20
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [myqueue, 2]
schedule:
  HackerNews:
    every: 1m